# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_desk', '0002_week_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignment_desk.Role'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='staffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='editorial_staff.Staffer'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignment_desk.Week'),
        ),
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='assignment_desk.RoleType'),
        ),
        migrations.AlterField(
            model_name='week',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='assignment_desk.RoleType'),
        ),
    ]
