# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_desk', '0005_auto_20180814_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='ending_date',
        ),
        migrations.AlterField(
            model_name='week',
            name='role_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='assignment_desk.RoleType'),
            preserve_default=False,
        ),
    ]
